language: ruby
rvm:
  - "2.3.0"
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - createdb naswApp_test
bundler_args: --binstubs=./bundler_stubs
